name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: "Docker image build & publish"
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          file_name: .env.production.local
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/terisikk/animeippo-frontend:latest
          cache-to: type=inline
          tags: ghcr.io/terisikk/animeippo-frontend:latest
